# This file is used to start the Inco local node and covalidator
# The canonical source of truth is https://github.com/Inco-fhevm/lightning-rod
# This file is a convenience for local development.

services:
  # Anvil node
  anvil:
    platform: linux/amd64 # mac compatibility
    image: inconetwork/local-node-anvil:v3-33-gc708d2f # Match https://github.com/Inco-fhevm/lightning-rod/blob/main/.env
    ports:
      - "8545:8545"

  # Covalidator service that waits for deployer to be healthy
  covalidator:
    platform: linux/amd64 # mac compatibility
    image: inconetwork/local-node-covalidator:v3-33-gc708d2f # Match https://github.com/Inco-fhevm/lightning-rod/blob/main/.env
    depends_on:
      anvil:
        condition: service_healthy
    ports:
      - "50055:50055"
